# .streamlit/secrets.toml
# Copie o conteúdo abaixo para o seu arquivo .streamlit/secrets.toml

[gcp_service_account]
# ... (Mantenha suas credenciais do Google aqui, como type, project_id, etc.) ...
# type = "service_account"
# project_id = "..."

[users]
# Defina aqui os usuários e senhas permitidos
admin = "admin"
montana = "montana"
# Adicione outros se necessário
# fulano = "senha_segura"
